version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN=2zYHyIijMAsVtUe0sssFODddynd_81mJ6oAvb1uL8RGsss55t
    command:
      - "http"
      - "--url=nonethic-cleo-exceptionable.ngrok-free.dev"
      - "3001"
